[schema]
# Vérifie que la monnaie est la même partout
currency = "EUR"

[invoice]
seller = """
L'Élysée
55 Rue du Faubourg Saint-Honoré
75008 Paris"""

customer = """
M et Mme Dupont
56 Rue du Faubourg Saint-Honoré
75008 Paris"""

footer = """
Règlement par chèque autorisé."""

# Pourcentage entre 0 et 1
tva = 0.20